### PR TITLE
An iteration from a fan.

### PR DESCRIPTION
**Pull request by vnjery1**
If you want continue the work, then do it but if you don't, please notify me in mainguyenpj@gmail.com, this is just my iteration of yours. I want to see it continue by its original creator but it seems nothing has changed since like 2 years ago. So, please, if you want to take my iteration, then here, it's not complete, because I want you to complete the rest. Hope that helps you.

### CODE REVIEW

**Comment by Caballero-Arepa** [comment]
Oh wow, I never thought I would have a fan for this.

I really, really appreciate what you are doing, this definitely motivate me to continue working on this.

I stopped working on this as I have a very busy life, and the Community project surged, but I've been wanting to come back, as I did recently some changes.

If you want to contribute more to the project, you are free to do so, and maybe even give you a collaborator role.
   In this case, I can share with you the plans I have.
   For now, I have most of the unit's planned out, and I'm designing the resource system.

So yeah, I'll gladly take your improvements, and hopefully this motivates me to resume on this.

**Comment by vnjery1** [comment]
Thanks, let me ask you, can I do more on the nations part because I want to
add more and changed some of those as well.

Vào 9:13, Th 5, 22 thg 6, 2023 Caballero Arepa ***@***.***>
đã viết:

**Comment by Caballero-Arepa** [comment]
Yeah, you can.

Of course, some of the national abilities will be changed depending on how the mod builds up, but in general I liked your job.

I liked your quotes, although I saw a few grammatical errors, but they are minor, and you still did a phenomenal job on them.

I see that you are Vietnamese, so you could add nations from Asia if you want.

**Comment by vnjery1** [comment]
Awesome, thank you so much!

Vào 9:22, Th 5, 22 thg 6, 2023 Caballero Arepa ***@***.***>
đã viết:

**Comment by Caballero-Arepa** [comment]
No, thanks to you _parce_

**Pull request merged**
