### PR TITLE
Random things I added

### PR DESCRIPTION
**Pull request by vnjery1**
I am sorry for the late response, just had a semester exam, anyway, here you go...
I have something that needs help:
-Uniques of City-states: They just show what type of the city-states is, not its uniques, which is sad.
-Natural Wonders: Please add more...
-Technology: Most are need quirks
-Music: Maybe some Romanticism Classical Music
-Is it weird because I added some nation icons and picture of Dom Pedro II of Brazil?
-Sounds for units
That's it. It's a huge list tho... I am sorry for this huge list. But still, let's keep the work going.

### CODE REVIEW

**Comment by vnjery1** [comment]
Hey, Cabarello-Arepa, keep doing the work, with your Latin American Nations. I have some ideas for scenario:
-Crimean War
-Napoleonic Wars (I think the Eagles Conquest could fit?)
-Opium Wars
-Scramble for Africa
-American Civil Warm
-Franco-Prussian War

**Comment by Caballero-Arepa** [comment]
Very interesting ideas!
I'll write them down to do them when it's finished

**Comment by Caballero-Arepa** [comment]
I'll have to do some edits, and then I'll merge it 👍
Hold up a bit

**Comment by vnjery1** [comment]
Please merge this, Caballero Arepa...
Please...

**Comment by Caballero-Arepa** [comment]
Alright, I was doing some changes first, and now its safe to merge your PR.

Thank you very much

**Pull request merged**
